/*ERROR: Se encontró una clase después del método main*/
//Se esperaba: EOF, se encontró class
class Prueba {

}
fn main () {

}
class Error {

}